export { roadsOptions } from './sbor-id/roads'
export { zamechaniyaOptions } from './construction-supervision/zamechaniya'
export { ustraneniyaZamechaniyOptions } from './construction-supervision/ustraneniya-zamechaniy'
export { approvedTransferByRoadsOptions } from './zadanie-na-proektirovanie/approved-transfer-by-roads'
export { approvedTransferByRoadsOptions as dashboard7ApprovedTransferByRoadsOptions } from './dashboard-7/approved-transfer-by-roads'
export { roadsOptions as dashboard6RoadsOptions } from './dashboard-6/roads'
export { roadsOptions as dogovorPirRoadsOptions } from './dogovor-pir/roads'
